### ISSUE TITLE
Erro de migração: variáveis cujo valor é uma ForeignKey

### ISSUE THREAD

**Issue by raianecardoso** [automatiza-mg/sima#5]
<img width="1440" alt="Captura de Tela 2024-07-23 às 15 28 40" src="https://github.com/user-attachments/assets/4946a025-6e5b-4549-8845-e66f861472c4">

**Comment by gabrielbdornas** [comment]
@raianecardoso, seu Issue ficou ótimo. Uma sugestão é incluir o código do erro no lugar do print. O código fica mais fácil no futuro de copiar e colar para pesquisas:

Exemplo:

```
models.PedidoImersao.usuario_id_apoio: (fields.E304) Reverse accessor 'Usuario.pedidoimersao_set' for 'models.PedidoImersao.usuario_id_apoio' clashes with reverse accessor for 'models.PedidoImersao.usuario_id_principal'.
	HINT: Add or change a related_name argument to the definition for 'models.PedidoImersao.usuario_id_apoio' or 'models.PedidoImersao.usuario_id_principal'.
models.PedidoImersao.usuario_id_principal: (fields.E304) Reverse accessor 'Usuario.pedidoimersao_set' for 'models.PedidoImersao.usuario_id_principal' clashes with reverse accessor for 'models.PedidoImersao.usuario_id_apoio'.
	HINT: Add or change a related_name argument to the definition for 'models.PedidoImersao.usuario_id_principal' or 'models.PedidoImersao.usuario_id_apoio'.
```

**Comment by gabrielbdornas** [comment]
Resposta do chatGpt para o problema:

To add two fields in a Django model that both point to the same ForeignKey column/table, you need to define each field as a separate ForeignKey relationship. Here is an example demonstrating how to do this:

Let's say you have a `Person` model and you want to create a `Task` model where each task has an `assigned_to` and a `reviewed_by` field, both pointing to the `Person` model.

1. Define your `Person` model:
    ```python
    from django.db import models

    class Person(models.Model):
        name = models.CharField(max_length=100)

        def __str__(self):
            return self.name
    ```

2. Define your `Task` model with two ForeignKey fields pointing to the `Person` model:
    ```python
    class Task(models.Model):
        title = models.CharField(max_length=200)
        assigned_to = models.ForeignKey(Person, related_name='tasks_assigned', on_delete=models.CASCADE)
        reviewed_by = models.ForeignKey(Person, related_name='tasks_reviewed', on_delete=models.CASCADE)

        def __str__(self):
            return self.title
    ```

### Explanation:

- `related_name`: This parameter is used to specify the name of the reverse relation from the `Person` model back to the `Task` model. Since there are two ForeignKey fields pointing to `Person`, you must provide unique `related_name` values to avoid conflicts.
- `on_delete`: This parameter specifies what should happen when the referenced `Person` is deleted. `models.CASCADE` means that when the referenced `Person` is deleted, the related `Task` instances will also be deleted.

### Complete Example:

```python
from django.db import models

class Person(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Task(models.Model):
    title = models.CharField(max_length=200)
    assigned_to = models.ForeignKey(Person, related_name='tasks_assigned', on_delete=models.CASCADE)
    reviewed_by = models.ForeignKey(Person, related_name='tasks_reviewed', on_delete=models.CASCADE)

    def __str__(self):
        return self.title
```

After defining your models, you need to create and apply the migrations to update the database schema:

```bash
python manage.py makemigrations
python manage.py migrate
```

This will create the necessary database tables and relationships to support your models with multiple ForeignKey fields pointing to the same table.

Faz muito sentido com o HINT fornecido pelo próprio erro:

>  HINT: Add or change a related_name argument to the definition for 'models.PedidoImersao.usuario_id_apoio' or 'models.PedidoImersao.usuario_id_principal'.
> HINT: Add or change a related_name argument to the definition for 'models.PedidoImersao.usuario_id_principal' or 'models.PedidoImersao.usuario_id_apoio'.
